routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@getLogin');

Route::get('login', 'HomeController@getLogin')->name('login');
Route::post('login', 'HomeController@postLogin')->name('login');
Route::get('logout', 'HomeController@getLogout')->name('logout');

Route::group(array('prefix'=>'admin', 'as' => 'admin.', 'middleware'=>'auth:users'), function(){
	Route::get('/', 'HomeController@getIndex');
	Route::get('index', 'HomeController@getIndex')->name('index');

    Route::resource('periode', 'PeriodeController');
    Route::post('periode/activate', 'PeriodeController@setAktifPeriode');
    Route::resource('fakultas', 'FakultasController');
    Route::resource('prodi', 'ProdiController');
    
    Route::resource('admin_fakultas', 'AdminFakultasController');
    Route::resource('mahasiswa', 'MahasiswaController');

    Route::resource('prestasi', 'PrestasiController');
    Route::resource('pendidikan', 'RiwayatPendidikanController');
    Route::resource('karya', 'KaryaController');
    Route::resource('penelitian', 'PenelitianController');
    Route::resource('organisasi', 'OrganisasiController');
    Route::resource('pekerjaan', 'PengalamanPekerjaanController');
    Route::resource('sertifikat', 'SertifikasiController');
    
});

Route::group(array('prefix' => 'mahasiswa', 'as' => 'mahasiswa.', 'namespace' => 'Mahasiswa','middleware'=>'auth:mahasiswa'), function(){
	Route::get('/', 'HomeController@getIndex');
	Route::get('index', 'HomeController@getIndex')->name('index');
    Route::get('print/{lang}', 'HomeController@getPrint')->name('print');
    Route::get('profil', 'HomeController@getProfil');
    Route::post('profil', 'HomeController@postProfil');

    Route::resource('karya', 'KaryaController');
    Route::resource('organisasi', 'OrganisasiController');
    Route::resource('pekerjaan', 'PengalamanKerjaController');
    Route::resource('prestasi', 'PrestasiController');
    Route::resource('penelitian', 'PenelitianController');
    Route::resource('pendidikan', 'RiwayatPendidikanController');
    Route::resource('sertifikat', 'SertifikasiController');
});

Route::get('/images/{filename}', function ($filename)
{
    $path = storage_path() . '/app/public/' . $filename;

    if(!File::exists($path)) return abort('404');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('/images/mahasiswa/{filename}', function ($filename)
{
    $path = storage_path() . '/app/mahasiswa/' . $filename;

    if(!File::exists($path)) return abort('404');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::group(array('prefix' => 'images', 'as' => 'images'), function(){

    Route::get('pendidikan/{filename}', 'ImageDownloadController@getImageRiwayatPendidikan');

    Route::get('prestasi/kegiatan/{filename}', 'ImageDownloadController@getImageKegiatanPrestasi');
    Route::get('prestasi/sertifikat/{filename}', 'ImageDownloadController@getImageSertifikatPrestasi');

    Route::get('sertifikat/{filename}', 'ImageDownloadController@getImageSertifikat');

    Route::get('karya/{filename}', 'ImageDownloadController@getImageKarya');

    Route::get('penelitian/{filename}', 'ImageDownloadController@getImagePenelitian');

    Route::get('organisasi/{filename}', 'ImageDownloadController@getImageOrganisasi');

    Route::get('pekerjaan/{filename}', 'ImageDownloadController@getImagePekerjaan');

});

resources/views/admin/dashboard.blade.php
@extends('layouts.admin_layout')
@section('css')
<link rel="stylesheet" type="text/css" href="/css/dataTables.bootstrap.min.css">
@stop
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Dashboard
    </h1>
    <ol class="breadcrumb">
      <li><a href="/admin/index"><i class="fa fa-home"></i> Dashboard</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Info boxes -->
    <div class="row">
      <div class="col-md-12">
        <div class="box box-danger">
          <div class="box-header">
            <h3 class="box-title">Total Pengajuan Portofolio</h3>
          </div>
          <div class="box-body">
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12">
                  <div class="info-box bg-yellow">
                    <span class="info-box-icon"><i class="fa fa-trophy"></i></span>

                    <div class="info-box-content">
                      <span class='info-box-text'>Prestasi</span>
                      <span class="info-box-number">{{$prestasi}}</span>
                      <span class="progress-description" style="margin-top: 12px;">
                        <a href="{{route('admin.prestasi.index')}}" style="text-decorations:none; color:inherit;"><b>Selengkapnya</b></a>
                      </span>
                    </div>
                    <!-- /.info-box-content -->
                  </div>
                  <!-- /.info-box -->
                </div>
                <!-- /.col -->
                <div class="col-md-3 col-sm-6 col-xs-12">
                  <div class="info-box bg-red">
                    <span class="info-box-icon"><i class="fa fa-paint-brush"></i></span>

                    <div class="info-box-content">
                      <span class="info-box-text">Sertifikat & Keahlian</span>
                      <span class="info-box-number">{{$sertifikasi}}</span>
                      <span class="progress-description" style="margin-top: 12px;">
                        <a href="{{route('admin.sertifikat.index')}}" style="text-decorations:none; color:inherit;"><b>Selengkapnya</b></a>
                      </span>
                    </div>
                    <!-- /.info-box-content -->
                  </div>
                  <!-- /.info-box -->
                </div>

                <!-- /.col -->
                <!-- fix for small devices only -->
                <div class="clearfix visible-sm-block"></div>

                <div class="col-md-3 col-sm-6 col-xs-12">
                  <div class="info-box bg-green">
                    <span class="info-box-icon"><i class="fa fa-rocket"></i></span>

                    <div class="info-box-content">
                      <span class="info-box-text">Karya & Penelitian</span>
                      <b>Karya Personal {{$karya}}</b><br>
                      <b>Penelitian Ilmiah {{$penelitian}}</b>
                      <span class="progress-description" style="margin-top: 5px;">
                        <a href="{{route('admin.penelitian.index')}}" style="text-decorations:none; color:inherit;"><b>Selengkapnya</b></a>
                      </span>
                    </div>
                    <!-- /.info-box-content -->
                  </div>
                  <!-- /.info-box -->
                </div>
                <!-- /.col -->
                <div class="col-md-3 col-sm-6 col-xs-12">
                  <div class="info-box bg-aqua">
                    <span class="info-box-icon"><i class="fa fa-sitemap"></i></span>

                    <div class="info-box-content">
                      <span class="info-box-text">Pengalaman</span>
                      <b>Organisasi {{$pekerjaan}}</b><br>
                      <b>Pekerjaan {{$pekerjaan}}</b>
                      <span class="progress-description" style="margin-top: 5px;">
                        <a href="{{route('admin.pekerjaan.index')}}" style="text-decorations:none; color:inherit;"><b>Selengkapnya</b></a>
                      </span>
                    </div>
                    <!-- /.info-box-content -->
                  </div>
                  <!-- /.info-box -->
                </div>

                <!-- /.col -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- detail News Modal -->
  

  @endsection
  @section('js')
  <script src="{{ asset('/js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('/js/dataTables.bootstrap.js') }}"></script>
  @stop

resources/views/admin/index.blade.php
@extends('layouts.admin_layout')
@push('css')
  <link rel="stylesheet" type="text/css" href="/css/dataTables.bootstrap.min.css">
@endpush
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Fakultas
      </h1>
      <ol class="breadcrumb">
        <li><a href="/admin/index"><i class="fa fa-home"></i> Dashboard</a></li>
        <li class="active"><a href="/administrator/admin">Fakultas</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class='box box-warning'>
            <div class="box-header">
              <i class="fa fa-user-secret"></i>
              <h3 class="box-title">Fakultas</h3>
              <button class="btn btn-sm btn-primary pull-right" data-toggle='modal' data-target="#createModal">Tambah Fakultas</button>
            </div>
            <div class="box-body">
              <table class="table table-striped table-bordered dataTable">
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Nama Fakultas</th>
                    <th>Aksi</th>
                  </tr>                  
                </thead>
                <tbody>
                  @foreach($data as $i =>  $d)
                  <tr>
                    <td>{{++$i}}</td>
                    <td>{{$d->nama}}</td>
                    <td>
                      <a href="#" class="edit btn btn-xs btn-primary" data-id='{{$d->id}}' data-year='{{$d->tahun}}' ><i class="fa fa-pencil"></i></a>
                      <a href="#" class="delete btn btn-xs btn-danger" data-id='{{$d->id}}' data-year='{{$d->tahun}}' ><i class="fa fa-times"></i></a>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- End Row-->
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- crate Class Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id='createModal'>
    <div class="modal-dialog" role="document">
      <form action="/admin/periode" method="post">
        <div class="modal-content">
          <div class="modal-header">
            <strong>Tambah Periode</strong><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
          </div>
          <div class="modal-body">
            <div class="col-md-12">
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-feed"></i></span>
                  <input type="text" class="form-control" placeholder="Tahun" name="tahun">
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
              {{csrf_field()}}
              <button type="button" class="btn btn-sm" data-dismiss="modal">Batal</button>
              <button type="submit" class="btn btn-sm btn-primary pull-right">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <!--Detail Class Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id='detailModal'>
    <div class="modal-dialog" role="document">
      <form action="/admin/periode" method="post" id="edit-form">
        <div class="modal-content">
          <div class="modal-header">
            <strong>Detail Periode</strong><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
          </div>
          <div class="modal-body">
            <div class="col-md-12">
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-feed"></i></span>
                  <input type="text" class="form-control" placeholder="Tahun" id='detailYear' name="tahun">
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
              {{csrf_field()}}
               {!! method_field('patch') !!}
              <input type="hidden" name="_id" value="" id="detailId">
              <button type="button" class="btn btn-sm" data-dismiss="modal">Batal</button>
              <button type="submit" class="btn btn-sm btn-primary pull-right">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  @endsection
  @push('js')
    <script src="{{ asset('/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('/js/dataTables.bootstrap.js') }}"></script>
    <script>
      $(document).ready(function() {
        $('.dataTable').dataTable();
      });

      $('.activate').click(function(){
        var year = $(this).data('year');
        var id = $(this).data('id');
        var _token = '{{csrf_token()}}';

        bootbox.confirm("<b>Aktifkan Periode</b> : <strong>"+year+"</strong> ?", function(result) {
          if (result) {
            toastr.options.timeOut = 0;
            toastr.options.extendedTimeOut = 0;
            toastr.info('<i class="fa fa-spinner fa-spin"></i><br>Process...');
            toastr.options.timeOut = 5000;
            toastr.options.extendedTimeOut = 1000;
            $.post("/admin/periode/activate", {id: id, _token:_token,})
            .done(function(result) {
              window.location.replace("/admin/periode/");
            })
            .fail(function(result) {
              toastr.clear();
              toastr.error('Server Error! Please reload this page again.');
            });
          };
        });
      });

      $('.edit').click(function(){
        var year = $(this).data('year');
        var id = $(this).data('id');
        $("#edit-form").attr("action", "/admin/periode/" + id);

        $('#detailYear').val(year);
        $('#detailId').val(id);
        $('#detailModal').modal();

      });
      $('.delete').click(function() {
        var id = $(this).data('id');
        var year = $(this).data('year');
        var _method = 'delete';
        var _token = '{{csrf_token()}}';

        bootbox.confirm("<b>Hapus Periode</b> : <strong>"+year+" </strong> ?", function(result) {
          if (result) {
            toastr.options.timeOut = 0;
            toastr.options.extendedTimeOut = 0;
            toastr.info('<i class="fa fa-spinner fa-spin"></i><br>Process...');
            toastr.options.timeOut = 5000;
            toastr.options.extendedTimeOut = 1000;
            $.post("/admin/periode/"+id, {id: id, _token:_token, _method:_method})
            .done(function(result) {
              window.location.replace("/admin/periode/");
            })
            .fail(function(result) {
              toastr.clear();
              toastr.error('Server Error! Please reload this page again.');
            });
          };
        });
      });
    </script>
  @endpush